将统计任务加入爬虫脚本

diff --git a/script/crawl b/script/crawl
--- a/script/crawl
+++ b/script/crawl
@@ -1,10 +1,12 @@
 #!/bin/bash
 
+VERSION=1.0-SNAPSHOT
+
 i=1
 while [ $i -le 15 ];
 do
 	echo "Run Generator Task ..."
-	hadoop jar sewing-1.0-SNAPSHOT.jar com.sidooo.sewing.Generator
+	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Generator
 	if [ $? -ne 0 ] 
 	then 
 		echo "Generator Task Fail."
@@ -12,10 +14,18 @@ do
 	fi
 	
 	echo "Run Crawl Task ..."
-	hadoop jar sewing-1.0-SNAPSHOT.jar com.sidooo.sewing.Crawl
+	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Crawl
 	if [ $? -ne 0 ]
 	then 
-		echo "Crawk Task Fail."
+		echo "Crawl Task Fail."
+		break;
+	fi
+	
+	echo "Run Count Task ..."
+	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Counter
+	if [ $? -ne 0 ]
+	then 
+		echo "Counter Task Fail."
 		break;
 	fi
 	
